use anyhow::{bail, Result};
use clap::{CommandFactory, ValueEnum};
use clap_complete::Shell as CompletionShell;
use std::io;

#[derive(Copy, Clone, Debug, ValueEnum, PartialEq, Eq)]
pub enum HookShell {
    Bash,
    Zsh,
}

impl HookShell {
    fn from_env() -> Option<Self> {
        let shell = std::env::var("SHELL").ok()?;
        let base = std::path::Path::new(&shell)
            .file_name()
            .and_then(|s| s.to_str())?;
        match base {
            "bash" => Some(HookShell::Bash),
            "zsh" => Some(HookShell::Zsh),
            _ => None,
        }
    }
}

pub fn run_init(shell: Option<HookShell>) -> Result<()> {
    let shell = match shell.or_else(HookShell::from_env) {
        Some(s) => s,
        None => bail!(
            "could not detect shell; pass one explicitly: `berth shell-init bash|zsh`"
        ),
    };
    print!("{}", init_script(shell));
    Ok(())
}

pub fn run_completions(shell: Option<CompletionShell>) -> Result<()> {
    let shell = match shell {
        Some(s) => s,
        None => detect_completion_shell()
            .ok_or_else(|| anyhow::anyhow!(
                "could not detect shell; pass one explicitly: `berth shell-completions bash|zsh|fish|elvish|powershell`"
            ))?,
    };
    let mut cmd = crate::cli::Cli::command();
    clap_complete::generate(shell, &mut cmd, "berth", &mut io::stdout());
    Ok(())
}

fn detect_completion_shell() -> Option<CompletionShell> {
    let shell = std::env::var("SHELL").ok()?;
    let base = std::path::Path::new(&shell)
        .file_name()
        .and_then(|s| s.to_str())?;
    match base {
        "bash" => Some(CompletionShell::Bash),
        "zsh" => Some(CompletionShell::Zsh),
        "fish" => Some(CompletionShell::Fish),
        "elvish" => Some(CompletionShell::Elvish),
        "pwsh" | "powershell" => Some(CompletionShell::PowerShell),
        _ => None,
    }
}

fn init_script(shell: HookShell) -> String {
    let common = COMMON_PRELUDE;
    let body = match shell {
        HookShell::Bash => BASH_HOOK,
        HookShell::Zsh => ZSH_HOOK,
    };
    format!("{common}\n{body}\n{COMMON_EPILOGUE}\n")
}

const COMMON_PRELUDE: &str = r#"# berth shell integration (cascading)
# Generated by `berth shell-init`. Re-run after upgrading berth.
#
# Auto-entry signal cascade for new tabs:
#   1. WezTerm/iTerm2 user var       (pane-scoped, doesn't cross tabs yet)
#   2. BERTH_PROJECT_HINT env var    (explicit override)
#   3. OSC 7 inherited PWD marker    (universal; how new tabs actually work)
#
# When the marker path is detected, the hook `cd`s to $HOME *before*
# invoking `berth enter`, so the user is never parked in the marker dir.

_berth_state_dir() {
    printf '%s/berth/active' "${XDG_STATE_HOME:-$HOME/.local/state}"
}

_berth_detect_project() {
    if [ -n "${WEZTERM_USER_VAR_BERTH_PROJECT:-}" ]; then
        printf '%s' "$WEZTERM_USER_VAR_BERTH_PROJECT"
        return 0
    fi
    if [ -n "${BERTH_PROJECT_HINT:-}" ]; then
        printf '%s' "$BERTH_PROJECT_HINT"
        return 0
    fi
    local state_dir
    state_dir="$(_berth_state_dir)"
    case "$PWD/" in
        "$state_dir"/*/*)
            local rest="${PWD#$state_dir/}"
            printf '%s' "${rest%%/*}"
            return 0
            ;;
        "$state_dir"/*)
            local rest="${PWD#$state_dir/}"
            printf '%s' "$rest"
            return 0
            ;;
    esac
    return 1
}

_berth_auto_enter_on_start() {
    [ -n "${BERTH_SKIP_AUTO:-}" ] && return 0
    [ -n "${BERTH_WORKSPACE:-}" ] && return 0
    case "$-" in
        *i*) : ;;
        *) return 0 ;;
    esac
    local proj
    proj="$(_berth_detect_project)" || return 0
    [ -z "$proj" ] && return 0
    # If we landed in the OSC 7 marker dir, leave it before doing anything
    # visible — the marker carries our signal, not a place we want to stay.
    local state_dir
    state_dir="$(_berth_state_dir)"
    case "$PWD/" in
        "$state_dir"/*) cd "$HOME" 2>/dev/null || cd / ;;
    esac
    export BERTH_SKIP_AUTO=1
    command berth enter "$proj"
}

# Defensive: if $PWD has vanished out from under us (older berth versions
# created and then deleted a state dir while a shell was cwd'd inside it),
# silently cd $HOME so direnv, getwd(), and `cd ..` stop failing on every
# prompt. Cheap to keep; harmless when $PWD is fine.
_berth_cwd_heal() {
    [ -d "$PWD" ] && return 0
    cd "$HOME" 2>/dev/null || cd /
}

b() {
    if [ "$#" -eq 0 ]; then
        command berth list
        return $?
    fi
    BERTH_SKIP_AUTO=1 command berth enter "$@"
}

berth() {
    case "${1:-}" in
        enter)
            shift
            BERTH_SKIP_AUTO=1 command berth enter "$@"
            ;;
        *)
            command berth "$@"
            ;;
    esac
}
"#;

const BASH_HOOK: &str = r#"# bash: run detection once per interactive shell start, and self-heal
# the cwd before every prompt.
if [ -n "${BASH_VERSION:-}" ]; then
    case ";${PROMPT_COMMAND:-};" in
        *";_berth_cwd_heal;"*) : ;;
        *) PROMPT_COMMAND="_berth_cwd_heal;${PROMPT_COMMAND:+$PROMPT_COMMAND}" ;;
    esac
    _berth_auto_enter_on_start
fi
"#;

const ZSH_HOOK: &str = r#"# zsh: same — run once at startup, plus precmd self-heal.
if [ -n "${ZSH_VERSION:-}" ]; then
    autoload -Uz add-zsh-hook
    add-zsh-hook precmd _berth_cwd_heal
    _berth_auto_enter_on_start
fi
"#;

const COMMON_EPILOGUE: &str = r#"# end berth shell integration
"#;
