use anyhow::{bail, Result};
use clap::{CommandFactory, ValueEnum};
use clap_complete::Shell as CompletionShell;
use std::io;

#[derive(Copy, Clone, Debug, ValueEnum, PartialEq, Eq)]
pub enum HookShell {
    Bash,
    Zsh,
}

impl HookShell {
    fn from_env() -> Option<Self> {
        let shell = std::env::var("SHELL").ok()?;
        let base = std::path::Path::new(&shell)
            .file_name()
            .and_then(|s| s.to_str())?;
        match base {
            "bash" => Some(HookShell::Bash),
            "zsh" => Some(HookShell::Zsh),
            _ => None,
        }
    }
}

pub fn run_init(shell: Option<HookShell>) -> Result<()> {
    let shell = match shell.or_else(HookShell::from_env) {
        Some(s) => s,
        None => bail!("could not detect shell; pass one explicitly: `berth shell-init bash|zsh`"),
    };
    print!("{}", init_script(shell));
    Ok(())
}

pub fn run_completions(shell: Option<CompletionShell>) -> Result<()> {
    let shell = match shell {
        Some(s) => s,
        None => detect_completion_shell()
            .ok_or_else(|| anyhow::anyhow!(
                "could not detect shell; pass one explicitly: `berth shell-completions bash|zsh|fish|elvish|powershell`"
            ))?,
    };
    let mut cmd = crate::cli::Cli::command();
    clap_complete::generate(shell, &mut cmd, "berth", &mut io::stdout());
    Ok(())
}

fn detect_completion_shell() -> Option<CompletionShell> {
    let shell = std::env::var("SHELL").ok()?;
    let base = std::path::Path::new(&shell)
        .file_name()
        .and_then(|s| s.to_str())?;
    match base {
        "bash" => Some(CompletionShell::Bash),
        "zsh" => Some(CompletionShell::Zsh),
        "fish" => Some(CompletionShell::Fish),
        "elvish" => Some(CompletionShell::Elvish),
        "pwsh" | "powershell" => Some(CompletionShell::PowerShell),
        _ => None,
    }
}

fn init_script(shell: HookShell) -> String {
    let common = COMMON_PRELUDE;
    let body = match shell {
        HookShell::Bash => BASH_HOOK,
        HookShell::Zsh => ZSH_HOOK,
    };
    format!("{common}\n{body}\n{COMMON_EPILOGUE}\n")
}

const COMMON_PRELUDE: &str = r#"# berth shell integration (cascading)
# Generated by `berth shell-init`. Re-run after upgrading berth.
#
# Auto-entry signal cascade for new tabs:
#   1. WezTerm/iTerm2 user var       (pane-scoped, doesn't cross tabs yet)
#   2. BERTH_PROJECT_HINT env var    (explicit override)
#   3. OSC 7 inherited PWD marker    (universal; how new tabs actually work)
#   4. ~/.local/state/berth/last-active (WSL+WinTerm fallback, time-gated)
#
# When the marker path is detected, the hook `cd`s to $HOME *before*
# invoking `berth enter`, so the user is never parked in the marker dir.
#
# OPT OUT (one shot):   BERTH_SKIP_AUTO=1 <command>
# OPT OUT (this shell): export BERTH_SKIP_AUTO=1

_berth_state_dir() {
    printf '%s/berth/active' "${XDG_STATE_HOME:-$HOME/.local/state}"
}

_berth_detect_project() {
    if [ -n "${WEZTERM_USER_VAR_BERTH_PROJECT:-}" ]; then
        printf '%s' "$WEZTERM_USER_VAR_BERTH_PROJECT"
        return 0
    fi
    if [ -n "${BERTH_PROJECT_HINT:-}" ]; then
        printf '%s' "$BERTH_PROJECT_HINT"
        return 0
    fi
    local state_dir dir_name canonical
    state_dir="$(_berth_state_dir)"
    case "$PWD/" in
        "$state_dir"/*/*)
            local rest="${PWD#$state_dir/}"
            dir_name="${rest%%/*}"
            ;;
        "$state_dir"/*)
            dir_name="${PWD#$state_dir/}"
            ;;
        *)
            return 1
            ;;
    esac
    # Prefer the canonical name written by `berth enter` (preserves
    # slashes); fall back to the directory basename only if the marker
    # file is missing (legacy / external state).
    if [ -r "$state_dir/$dir_name/.workspace" ]; then
        canonical="$(cat "$state_dir/$dir_name/.workspace" 2>/dev/null)"
        [ -n "$canonical" ] && { printf '%s' "$canonical"; return 0; }
    fi
    printf '%s' "$dir_name"
    return 0
}

_berth_auto_enter_on_start() {
    [ -n "${BERTH_SKIP_AUTO:-}" ] && return 0
    [ -n "${BERTH_WORKSPACE:-}" ] && return 0
    case "$-" in
        *i*) : ;;
        *) return 0 ;;
    esac

    local state_dir invoke_file invoke_line proj
    state_dir="$(_berth_state_dir)"

    # 1. Cwd-inheritance path: detect workspace from $PWD if it's inside
    #    the marker dir tree. Hop out to $HOME before doing anything
    #    visible so the user is never parked in the state dir.
    proj="$(_berth_detect_project 2>/dev/null)" || proj=""
    if [ -n "$proj" ]; then
        case "$PWD/" in
            "$state_dir"/*) cd "$HOME" 2>/dev/null || cd / ;;
        esac
        invoke_file="$state_dir/$(printf '%s' "$proj" | sed 's|/|_|g')/.invoke"
        if [ -r "$invoke_file" ]; then
            # eval the exact `berth enter --new <ws> [--dir D] [-- argv]`
            # line written by the parent tab. Replays workspace + dir +
            # command override verbatim. Prefix-guard the contents so a
            # same-uid process planting a different shape can only run
            # `berth enter --new …`, not arbitrary commands.
            invoke_line="$(cat "$invoke_file" 2>/dev/null)"
            case "$invoke_line" in
                "BERTH_SKIP_AUTO=1 command berth enter --new "*)
                    eval "$invoke_line"
                    return $?
                    ;;
            esac
        fi
        # Fall back to bare invocation if marker exists but no .invoke.
        export BERTH_SKIP_AUTO=1
        command berth enter --new "$proj"
        return $?
    fi

    # 2. Fallback path: cwd inheritance failed (e.g. WSL + Windows
    #    Terminal can't honor OSC 7 paths pointing at the remote box).
    #    Read the global last-active pointer — last writer wins. Tight
    #    time gate (10 min) bounds the window in which a same-uid
    #    process planting this file could get arbitrary code eval'd
    #    in the user's next interactive shell. The expected workflow
    #    (open new tab seconds-to-minutes after `berth enter`) fits
    #    comfortably inside this window.
    local last_file
    last_file="${XDG_STATE_HOME:-$HOME/.local/state}/berth/last-active"
    if [ -r "$last_file" ]; then
        if [ -n "$(find "$last_file" -mmin -10 2>/dev/null)" ]; then
            invoke_line="$(cat "$last_file" 2>/dev/null)"
            # Defense-in-depth: only eval lines that match the exact
            # shape berth writes. An attacker who pre-creates this file
            # is constrained to invoking `berth enter --new …`, not
            # arbitrary shell.
            case "$invoke_line" in
                "BERTH_SKIP_AUTO=1 command berth enter --new "*)
                    eval "$invoke_line"
                    return $?
                    ;;
            esac
        fi
    fi
    return 0
}

# Defensive: if $PWD has vanished out from under us (older berth versions
# created and then deleted a state dir while a shell was cwd'd inside it),
# silently cd $HOME so direnv, getwd(), and `cd ..` stop failing on every
# prompt. Cheap to keep; harmless when $PWD is fine.
_berth_cwd_heal() {
    [ -d "$PWD" ] && return 0
    cd "$HOME" 2>/dev/null || cd /
}

_berth_workspace_names() {
    command berth list 2>/dev/null \
        | awk 'NR>2 && $1!="" && $1!~/^-+$/ {print $1}'
}

# `b` is the canonical shortcut for `berth enter`. Behavior:
#   b                  — interactive fzf picker over configured workspaces
#   b <query>          — exact-match a workspace name; on miss, fuzzy/substring match
#   b <query> <args…>  — pass extra args through (e.g. -- <cmd>)
# When fzf is available it powers both the no-arg picker and fuzzy filtering;
# otherwise we fall back to `grep -F` substring matching.
b() {
    local picked query
    if [ "$#" -eq 0 ]; then
        if command -v fzf >/dev/null 2>&1; then
            picked=$(_berth_workspace_names | fzf --prompt='berth> ' --height=40% --reverse) || return 0
            [ -z "$picked" ] && return 0
            BERTH_SKIP_AUTO=1 command berth enter "$picked"
            return $?
        fi
        printf 'usage: b <workspace>  (install fzf for an interactive picker)\n' >&2
        _berth_workspace_names
        return 1
    fi
    query="$1"; shift
    # Exact match wins.
    if _berth_workspace_names | grep -qFx -- "$query"; then
        BERTH_SKIP_AUTO=1 command berth enter "$query" "$@"
        return $?
    fi
    # Fuzzy / substring match → single canonical winner.
    if command -v fzf >/dev/null 2>&1; then
        picked=$(_berth_workspace_names | fzf --filter "$query" | head -n1)
    else
        picked=$(_berth_workspace_names | grep -F -- "$query" | head -n1)
    fi
    if [ -z "$picked" ]; then
        printf 'berth: no workspace matching %q\n' "$query" >&2
        return 1
    fi
    BERTH_SKIP_AUTO=1 command berth enter "$picked" "$@"
}

berth() {
    case "${1:-}" in
        enter)
            shift
            BERTH_SKIP_AUTO=1 command berth enter "$@"
            ;;
        *)
            command berth "$@"
            ;;
    esac
}
"#;

const BASH_HOOK: &str = r#"# bash: run detection once per interactive shell start, and self-heal
# the cwd before every prompt.
if [ -n "${BASH_VERSION:-}" ]; then
    case ";${PROMPT_COMMAND:-};" in
        *";_berth_cwd_heal;"*) : ;;
        *) PROMPT_COMMAND="_berth_cwd_heal;${PROMPT_COMMAND:+$PROMPT_COMMAND}" ;;
    esac
    _berth_auto_enter_on_start
fi
"#;

const ZSH_HOOK: &str = r#"# zsh: same — run once at startup, plus precmd self-heal.
if [ -n "${ZSH_VERSION:-}" ]; then
    autoload -Uz add-zsh-hook
    add-zsh-hook precmd _berth_cwd_heal
    _berth_auto_enter_on_start
fi
"#;

const COMMON_EPILOGUE: &str = r#"# end berth shell integration
"#;
