pub mod config;
pub mod discovery;
pub mod hosts;
pub mod lifecycle;
pub mod lifecycle_state;
pub mod runtime;
pub mod session;
pub mod ssh;
pub mod terminal;
pub mod tunnel;

pub const BERTH_DIR: &str = "berth";
pub const BERTH_CONFIG_FILE_YAML: &str = "config.yaml";
pub const BERTH_CONFIG_FILE_JSON: &str = "config.json";
pub const BERTH_PROJECTS_DIR: &str = "projects";

/// Strict allowlist for workspace names. The name flows into shell-interpolated
/// remote SSH commands, filesystem paths under `~/.local/share/berth/projects/`,
/// session socket paths, and terminal escape payloads — so we keep the
/// character set conservative and reject any segment that could traverse the
/// projects root.
///
/// Grammar: `segment ( '/' segment )?`
/// where  `segment` = `[A-Za-z0-9_.-]+` but is not `.` or `..`
pub fn validate_workspace_name(name: &str) -> anyhow::Result<()> {
    if name.is_empty() {
        anyhow::bail!("Invalid workspace name: cannot be empty");
    }
    let segments: Vec<&str> = name.split('/').collect();
    if segments.len() > 2 {
        anyhow::bail!(
            "Invalid workspace name '{}': only one slash allowed (org/project format)",
            name
        );
    }
    for seg in &segments {
        if seg.is_empty() {
            anyhow::bail!(
                "Invalid workspace name '{}': empty segment (leading, trailing, or double slash)",
                name
            );
        }
        if *seg == "." || *seg == ".." {
            anyhow::bail!(
                "Invalid workspace name '{}': '.' and '..' segments are not allowed",
                name
            );
        }
        if !seg
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.' || c == '-')
        {
            anyhow::bail!(
                "Invalid workspace name '{}': only ASCII letters, digits, '_', '.', '-' allowed (got segment '{}')",
                name,
                seg
            );
        }
    }
    Ok(())
}

/// Session ids are generated by `session::new_session_id()` as 12 lowercase
/// hex characters. When a user passes `--session <id>` we validate here so
/// no manually-supplied value can traverse paths or contain shell metas.
pub fn validate_session_id(id: &str) -> anyhow::Result<()> {
    if id.is_empty() || id.len() > 64 {
        anyhow::bail!("Invalid session id: must be 1..=64 chars");
    }
    if !id.chars().all(|c| c.is_ascii_alphanumeric()) {
        anyhow::bail!(
            "Invalid session id '{}': only ASCII letters and digits allowed",
            id
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_workspace_name_accepts_typical_forms() {
        for name in ["proj", "Proj-1", "org/proj", "a_b.c-d", "a/b-c.d_e"] {
            assert!(validate_workspace_name(name).is_ok(), "should accept {name}");
        }
    }

    #[test]
    fn validate_workspace_name_rejects_shell_metacharacters() {
        for name in [
            "foo;rm -rf /",
            "foo bar",
            "$(whoami)",
            "`whoami`",
            "foo\nbar",
            "foo|bar",
            "foo&bar",
            "foo>bar",
            "foo'bar",
            "foo\"bar",
        ] {
            assert!(
                validate_workspace_name(name).is_err(),
                "should reject {name}"
            );
        }
    }

    #[test]
    fn validate_workspace_name_rejects_traversal() {
        for name in ["..", ".", "../etc", "etc/..", "./foo", "foo/."] {
            assert!(
                validate_workspace_name(name).is_err(),
                "should reject {name}"
            );
        }
    }

    #[test]
    fn validate_workspace_name_rejects_slash_edges_and_doubles() {
        for name in ["/foo", "foo/", "foo//bar", "", "/", "a/b/c"] {
            assert!(
                validate_workspace_name(name).is_err(),
                "should reject {name}"
            );
        }
    }

    #[test]
    fn validate_session_id_accepts_typical_and_rejects_metas() {
        assert!(validate_session_id("abc123def456").is_ok());
        assert!(validate_session_id("a").is_ok());
        assert!(validate_session_id("").is_err());
        assert!(validate_session_id("../etc").is_err());
        assert!(validate_session_id("a-b").is_err());
        assert!(validate_session_id("a.b").is_err());
        assert!(validate_session_id(&"a".repeat(65)).is_err());
    }
}
