pub mod config;
pub mod deploy;
pub mod discovery;
pub mod hosts;
pub mod lifecycle;
pub mod lifecycle_state;
pub mod runtime;
pub mod session;
pub mod ssh;
pub mod terminal;
pub mod tunnel;

pub const BERTH_DIR: &str = "berth";
pub const BERTH_CONFIG_FILE_YAML: &str = "config.yaml";
pub const BERTH_CONFIG_FILE_JSON: &str = "config.json";
pub const BERTH_PROJECTS_DIR: &str = "projects";

/// Strict allowlist for workspace names. The name flows into shell-interpolated
/// remote SSH commands, filesystem paths under `~/.local/share/berth/projects/`,
/// session socket paths, and terminal escape payloads — so we keep the
/// character set conservative and reject any segment that could traverse the
/// projects root.
///
/// Grammar: `segment ( '/' segment )?`
/// where  `segment` = `[A-Za-z0-9_.-]+` but is not `.` or `..`
pub fn validate_workspace_name(name: &str) -> anyhow::Result<()> {
    if name.is_empty() {
        anyhow::bail!("Invalid workspace name: cannot be empty");
    }
    let segments: Vec<&str> = name.split('/').collect();
    if segments.len() > 2 {
        anyhow::bail!(
            "Invalid workspace name '{}': only one slash allowed (org/project format)",
            name
        );
    }
    for seg in &segments {
        if seg.is_empty() {
            anyhow::bail!(
                "Invalid workspace name '{}': empty segment (leading, trailing, or double slash)",
                name
            );
        }
        if *seg == "." || *seg == ".." {
            anyhow::bail!(
                "Invalid workspace name '{}': '.' and '..' segments are not allowed",
                name
            );
        }
        if !seg
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.' || c == '-')
        {
            anyhow::bail!(
                "Invalid workspace name '{}': only ASCII letters, digits, '_', '.', '-' allowed (got segment '{}')",
                name,
                seg
            );
        }
    }
    Ok(())
}

/// Reject SSH host arguments that would be parsed by `ssh`/`scp` as
/// options. OpenSSH treats any arg starting with `-` as a flag (e.g.
/// `-oProxyCommand=…`), so a host like `-oProxyCommand=cat /etc/passwd`
/// becomes arbitrary local-command execution under our user. Argv-style
/// invocation does *not* defend against this — only validation does.
pub fn validate_ssh_host(host: &str) -> anyhow::Result<()> {
    if host.is_empty() {
        anyhow::bail!("Invalid SSH host: cannot be empty");
    }
    if host.starts_with('-') {
        anyhow::bail!(
            "Invalid SSH host '{}': hosts may not start with '-' (would be parsed by ssh/scp as an option)",
            host
        );
    }
    // ssh allows `[user@][addr][:port]`. Reject ASCII control chars and
    // whitespace defensively; `ssh foo bar` would split into two args
    // under the hood already, so this is just belt+suspenders.
    if host
        .chars()
        .any(|c| c.is_ascii_control() || c == ' ' || c == '\t')
    {
        anyhow::bail!(
            "Invalid SSH host '{}': must not contain whitespace or control characters",
            host
        );
    }
    Ok(())
}

/// Validate a GitHub-release tag (used by `berth deploy --tag <tag>`).
/// Tags flow into a `PathBuf::join` for the binary cache, so we must
/// reject path-separator and traversal characters even though the tag
/// originates from the user's own CLI.
pub fn validate_release_tag(tag: &str) -> anyhow::Result<()> {
    if tag.is_empty() || tag.len() > 64 {
        anyhow::bail!("Invalid release tag: must be 1..=64 chars");
    }
    if !tag
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_' || c == '+')
    {
        anyhow::bail!(
            "Invalid release tag '{}': only ASCII letters, digits, '.', '-', '_', '+' allowed",
            tag
        );
    }
    if tag == "." || tag == ".." {
        anyhow::bail!("Invalid release tag '{}': '.' / '..' are reserved", tag);
    }
    Ok(())
}

/// Session ids are generated by `session::new_session_id()` as 12 lowercase
/// hex characters. When a user passes `--session <id>` we validate here so
/// no manually-supplied value can traverse paths or contain shell metas.
pub fn validate_session_id(id: &str) -> anyhow::Result<()> {
    if id.is_empty() || id.len() > 64 {
        anyhow::bail!("Invalid session id: must be 1..=64 chars");
    }
    if !id.chars().all(|c| c.is_ascii_alphanumeric()) {
        anyhow::bail!(
            "Invalid session id '{}': only ASCII letters and digits allowed",
            id
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_workspace_name_accepts_typical_forms() {
        for name in ["proj", "Proj-1", "org/proj", "a_b.c-d", "a/b-c.d_e"] {
            assert!(
                validate_workspace_name(name).is_ok(),
                "should accept {name}"
            );
        }
    }

    #[test]
    fn validate_workspace_name_rejects_shell_metacharacters() {
        for name in [
            "foo;rm -rf /",
            "foo bar",
            "$(whoami)",
            "`whoami`",
            "foo\nbar",
            "foo|bar",
            "foo&bar",
            "foo>bar",
            "foo'bar",
            "foo\"bar",
        ] {
            assert!(
                validate_workspace_name(name).is_err(),
                "should reject {name}"
            );
        }
    }

    #[test]
    fn validate_workspace_name_rejects_traversal() {
        for name in ["..", ".", "../etc", "etc/..", "./foo", "foo/."] {
            assert!(
                validate_workspace_name(name).is_err(),
                "should reject {name}"
            );
        }
    }

    #[test]
    fn validate_workspace_name_rejects_slash_edges_and_doubles() {
        for name in ["/foo", "foo/", "foo//bar", "", "/", "a/b/c"] {
            assert!(
                validate_workspace_name(name).is_err(),
                "should reject {name}"
            );
        }
    }

    #[test]
    fn validate_ssh_host_accepts_typical_forms() {
        for h in ["host", "user@host", "user@host.example.com", "192.0.2.1"] {
            assert!(validate_ssh_host(h).is_ok(), "should accept {h}");
        }
    }

    #[test]
    fn validate_ssh_host_rejects_option_like_args() {
        for h in ["-oProxyCommand=cat /etc/passwd", "-l", "--config=/dev/null"] {
            assert!(validate_ssh_host(h).is_err(), "should reject {h}");
        }
    }

    #[test]
    fn validate_ssh_host_rejects_whitespace_and_controls() {
        assert!(validate_ssh_host("").is_err());
        assert!(validate_ssh_host("a b").is_err());
        assert!(validate_ssh_host("a\tb").is_err());
        assert!(validate_ssh_host("a\nb").is_err());
    }

    #[test]
    fn validate_release_tag_accepts_semver_like_inputs() {
        for t in ["v0.1.0", "0.1.0", "1.2.3-rc.1", "v2024.05", "1.0.0+build.7"] {
            assert!(validate_release_tag(t).is_ok(), "should accept {t}");
        }
    }

    #[test]
    fn validate_release_tag_rejects_traversal_and_path_separators() {
        for t in [
            "../../tmp/foo",
            "v../bad",
            "v/foo",
            "v\\foo",
            "..",
            ".",
            "",
            "v$RANDOM",
            "v;rm -rf /",
        ] {
            assert!(validate_release_tag(t).is_err(), "should reject {t}");
        }
    }

    #[test]
    fn validate_session_id_accepts_typical_and_rejects_metas() {
        assert!(validate_session_id("abc123def456").is_ok());
        assert!(validate_session_id("a").is_ok());
        assert!(validate_session_id("").is_err());
        assert!(validate_session_id("../etc").is_err());
        assert!(validate_session_id("a-b").is_err());
        assert!(validate_session_id("a.b").is_err());
        assert!(validate_session_id(&"a".repeat(65)).is_err());
    }
}
